GET http://localhost:8090/balancesss
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTE3NTAzODYsIm5iZiI6MTY5MTc0MzE4NiwiaWF0IjoxNjkxNzQzMTg2LCJpc3MiOiIxIiwiYXVkIjoibWljcm9fdXNlciIsImp0aSI6Imp0aSIsInR5cCI6ImFjY2Vzc190b2tlbiIsInVzZXJfaWQiOiIxIiwidXNlcm5hbWUiOiJiaWxseSIsImVtYWlsIjoiYmlsbHlAZ21haWwuY29tIn0.FmQMzvyajC0veZveE6yI5s3_FuTRNQoVp-me0a0b2gs
