// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: modules/proto/email.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Email struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender        string  `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	NameReceiver  string  `protobuf:"bytes,3,opt,name=name_receiver,json=nameReceiver,proto3" json:"name_receiver,omitempty"`
	NameProduct   string  `protobuf:"bytes,4,opt,name=name_product,json=nameProduct,proto3" json:"name_product,omitempty"`
	Harga         float32 `protobuf:"fixed32,5,opt,name=harga,proto3" json:"harga,omitempty"`
	Qty           uint64  `protobuf:"varint,6,opt,name=qty,proto3" json:"qty,omitempty"`
	Total         float32 `protobuf:"fixed32,7,opt,name=total,proto3" json:"total,omitempty"`
	EmailReceiver string  `protobuf:"bytes,8,opt,name=email_receiver,json=emailReceiver,proto3" json:"email_receiver,omitempty"`
}

func (x *Email) Reset() {
	*x = Email{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_proto_email_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_email_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_modules_proto_email_proto_rawDescGZIP(), []int{0}
}

func (x *Email) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Email) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Email) GetNameReceiver() string {
	if x != nil {
		return x.NameReceiver
	}
	return ""
}

func (x *Email) GetNameProduct() string {
	if x != nil {
		return x.NameProduct
	}
	return ""
}

func (x *Email) GetHarga() float32 {
	if x != nil {
		return x.Harga
	}
	return 0
}

func (x *Email) GetQty() uint64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *Email) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Email) GetEmailReceiver() string {
	if x != nil {
		return x.EmailReceiver
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int64      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data  *EmailList `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error string     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_proto_email_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_email_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_modules_proto_email_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetData() *EmailList {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type EmailList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Email `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *EmailList) Reset() {
	*x = EmailList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_proto_email_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailList) ProtoMessage() {}

func (x *EmailList) ProtoReflect() protoreflect.Message {
	mi := &file_modules_proto_email_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailList.ProtoReflect.Descriptor instead.
func (*EmailList) Descriptor() ([]byte, []int) {
	return file_modules_proto_email_proto_rawDescGZIP(), []int{2}
}

func (x *EmailList) GetList() []*Email {
	if x != nil {
		return x.List
	}
	return nil
}

var File_modules_proto_email_proto protoreflect.FileDescriptor

var file_modules_proto_email_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdc, 0x01, 0x0a, 0x05,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x23, 0x0a,
	0x0d, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x61, 0x6d, 0x65, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x61, 0x72, 0x67, 0x61, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x68, 0x61, 0x72, 0x67, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x71,
	0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x71, 0x74, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x22, 0x54, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x27, 0x0a, 0x09, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0x2a, 0x0a, 0x08, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x53, 0x72, 0x76, 0x12, 0x1e, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x1a, 0x09, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1b, 0x5a, 0x19, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x5f, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_proto_email_proto_rawDescOnce sync.Once
	file_modules_proto_email_proto_rawDescData = file_modules_proto_email_proto_rawDesc
)

func file_modules_proto_email_proto_rawDescGZIP() []byte {
	file_modules_proto_email_proto_rawDescOnce.Do(func() {
		file_modules_proto_email_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_proto_email_proto_rawDescData)
	})
	return file_modules_proto_email_proto_rawDescData
}

var file_modules_proto_email_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_modules_proto_email_proto_goTypes = []interface{}{
	(*Email)(nil),     // 0: Email
	(*Response)(nil),  // 1: Response
	(*EmailList)(nil), // 2: EmailList
}
var file_modules_proto_email_proto_depIdxs = []int32{
	2, // 0: Response.data:type_name -> EmailList
	0, // 1: EmailList.list:type_name -> Email
	0, // 2: EmailSrv.SendEmail:input_type -> Email
	1, // 3: EmailSrv.SendEmail:output_type -> Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_modules_proto_email_proto_init() }
func file_modules_proto_email_proto_init() {
	if File_modules_proto_email_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_proto_email_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Email); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_proto_email_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_proto_email_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_proto_email_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_proto_email_proto_goTypes,
		DependencyIndexes: file_modules_proto_email_proto_depIdxs,
		MessageInfos:      file_modules_proto_email_proto_msgTypes,
	}.Build()
	File_modules_proto_email_proto = out.File
	file_modules_proto_email_proto_rawDesc = nil
	file_modules_proto_email_proto_goTypes = nil
	file_modules_proto_email_proto_depIdxs = nil
}
